name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Build with Gradle
        run: ./gradlew build
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          
      - name: Log in to DigitalOcean Docker Registry
        run: |
          doctl registry login
          
      - name: Build and publish Docker image
        run: |
          version=$(git rev-parse --short=8 HEAD)
          ./gradlew jib -Djib.to.tags=$version,latest 