---
name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed to push Git tags

jobs:
  build:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to DigitalOcean Docker Registry
        run: |
          doctl registry login

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle check
        run: ./gradlew clean check

      - name: Gradle release
        run: ./gradlew release

      - name: Propagate current release version
        id: tag_version
        run: |
          current_version=$(./gradlew currentVersion -q | grep "Project version" | awk '{print $3}')
          echo "Version set to: $current_version"
          echo "version=$current_version" >> $GITHUB_OUTPUT

      - name: Build and publish Docker image
        run: |
          version="${{ steps.tag_version.outputs.version }}"
          commit_hash=$(git rev-parse --short=8 HEAD)
          ./gradlew build jib -Djib.to.tags=$commit_hash,$version,latest
